[default_session]
startup_command = "nvim -c ':Telescope find_files'"

# example to setup the session using sesh
# [[session]]
# name = "tmux config test for session setting"
# path = "~/.config/tmux"
# startup_command = "nvim tmux.conf"
